ckanext/vocabulary_services/blueprint.py
import ckan.lib.navl.dictization_functions as dict_fns
import ckan.logic as logic
import ckan.plugins.toolkit as toolkit
import logging

from ckan.common import request
from ckanext.vocabulary_services import helpers
from ckanext.invalid_uris.helpers import valid_uri
from flask import Blueprint
from ckan.views.api import _finish_ok

clean_dict = logic.clean_dict
get_action = toolkit.get_action
h = toolkit.h
log = logging.getLogger(__name__)
parse_params = logic.parse_params
tuplize_dict = logic.tuplize_dict

vocabulary_services = Blueprint('vocabulary_services', __name__, url_prefix=u'/ckan-admin')


def index():

    helpers.check_access({})

    try:
        data = {}
        errors = {}
        is_update = False
        vocab_service_id = request.args.get('id')
        if request.method == 'POST':
            data = clean_dict(dict_fns.unflatten(tuplize_dict(parse_params(
                request.form))))
            try:
                if vocab_service_id:
                    get_action('vocabulary_service_edit')({}, data)
                    h.flash_success('Vocabulary service %s updated.' % data['title'])

                    return h.redirect_to('vocabulary_services.index')
                else:
                    get_action('vocabulary_service_create')({}, data)
                    h.flash_success('Vocabulary service %s added.' % data['title'])

                # Reset the form data.
                data = {}
            except toolkit.ValidationError as e:
                log.warn(e)
                errors = e.error_dict
                log.debug(errors)

                if vocab_service_id:
                    is_update = True
                    h.flash_error('Error updating vocabulary service %s.' % data['title'])
                else:
                    h.flash_error('Error adding vocabulary service %s.' % data['title'])

        elif request.method == 'GET' and vocab_service_id:
            is_update = True
            data = get_action('get_vocabulary_service')({}, vocab_service_id)

        services = get_action('get_vocabulary_services')({}, {})

        return toolkit.render('vocabulary/index.html',
                              extra_vars={
                                  'data': data,
                                  'errors': errors,
                                  'services': services,
                                  'is_update': is_update
                              })
    except Exception as e:
        log.error(e)
        toolkit.abort(503, str(e))


def refresh(id):

    helpers.check_access({})

    service = get_action('get_vocabulary_service')({}, id)

    if service:

        data_dict = {
            'id': service.id,
            'uri': service.uri,
        }

        # Validate uri.
        valid_uri_resp = valid_uri(data_dict.get('uri'))
        if not valid_uri_resp.get('valid'):
            h.flash_error('Uri is not valid.')
            return h.redirect_to('vocabulary_services.index')

        action = None

        if service.type == 'sparql_json':
            action = 'get_sparql_json_vocabulary_terms'
        elif service.type == 'remote_csv':
            action = 'get_remote_csv_vocabulary_terms'

        if action:
            if get_action(action)({}, data_dict):
                get_action('update_vocabulary_service_last_processed')({}, service.id)
                h.flash_success(
                    'Terms in vocabulary refreshed. <a href="{}">View terms</a>'.format(h.url_for('vocabulary_services.terms', id=service.id)),
                    allow_html=True
                )
        else:
            h.flash_error('Vocabulary service type %s not currently implemented.' % service.type)

    return h.redirect_to('vocabulary_services.index')


def terms(id):

    helpers.check_access({})

    return toolkit.render('vocabulary/terms.html',
                          extra_vars={
                              'vocabulary_service': get_action('get_vocabulary_service')({}, id),
                              'terms': get_action('get_vocabulary_service_terms')({}, id),
                          })


def delete(id):
    """
    Delete vocabulary service.
    """
    if request.method == 'POST':
        try:
            get_action('vocabulary_service_delete')({}, id)
            h.flash_success('Vocabulary service deleted.')
        except Exception as e:
            log.error(e)
            h.flash_error('Error deleting vocabulary service.')
    else:
        h.flash_error('Can not delete vocabulary service.')

    return h.redirect_to('vocabulary_services.index')


def vocabulary_service_term_autocomplete(term_name):
    q = request.args.get('incomplete', '')
    limit = request.args.get('limit', 5)
    search_dict = {'term_name': term_name, 'q': q, 'limit': limit}

    if not q:
        return _finish_ok({})

    result = get_action('vocabulary_service_term_search')({}, search_dict)
    if not result:
        return _finish_ok({})

    result_set = {'ResultSet': {u'Result': result}}

    return _finish_ok(result_set)


def vocabulary_service_term_json(term_name):
    result = get_action('get_vocabulary_service_terms')({}, term_name)
    if not result:
        return _finish_ok({})

    res = []
    for term in result:
        dict = term.__dict__
        dict.pop('_sa_instance_state')
        dict.pop('date_created')
        dict.pop('date_modified')
        dict['title'] = dict.get('label')
        dict['key'] = dict.get('uri')
        res.append(dict)

    return _finish_ok(helpers.render_hierarchical(res))


vocabulary_services.add_url_rule(u'/vocabulary-services', methods=[u'GET', u'POST'], view_func=index)
vocabulary_services.add_url_rule(u'/vocabulary-service/refresh/<id>', view_func=refresh)
vocabulary_services.add_url_rule(u'/vocabulary-service/terms/<id>', view_func=terms)
vocabulary_services.add_url_rule(u'/vocabulary-service/delete/<id>', methods=[u'POST'], view_func=delete)
vocabulary_services.add_url_rule(u'/vocabulary-service/term-autocomplete/<term_name>', view_func=vocabulary_service_term_autocomplete)
vocabulary_services.add_url_rule(u'/vocabulary-service/term-json/<term_name>', view_func=vocabulary_service_term_json)

ckanext/vocabulary_services/templates/vocabulary/index.html
{% extends "admin/base.html" %}

{% import 'macros/form.html' as form %}

{% block primary_content_inner %}
  {% asset 'vocabulary_services/add_edit_form' %}

  {% if is_update %}
    <h2>Edit vocabulary service: {{ data.title }}</h2>
  {% else %}
    <h2>Add a vocabulary service</h2>
  {% endif %}

  <form id="dataset-edit" class="dataset-form" method="post" action="{{ h.url_for('vocabulary_services.index', id=data.id) if is_update else h.url_for('vocabulary_services.index')}}" novalidate>
    {{ h.csrf_input() }}
    {{ form.input(
      'title',
      id='field-title',
      label=_('Title'),
      value=data.title,
      error=errors.title,
      classes=['control-medium'],
      is_required=True
    ) }}

    {%
      set schemas = [
        {'text': 'Please select a schema', 'value': ''},
        {'text': 'Dataset', 'value': 'dataset__dataset_fields'},
        {'text': 'Data service', 'value': 'dataservice__dataset_fields'},
        {'text': 'Distribution', 'value': 'dataset__resource_fields'}
      ]
    %}
    {{ form.select(
        'schema',
        label=_('Schema'),
        options=schemas,
        selected=data.schema,
        error=errors.schema,
        is_required=True
    ) }}

    {% set linked_schema_field = h.get_linked_schema_field_options(services, data) %}
    <script>
      var linked_schema_field = {{ linked_schema_field|tojson }}
      var linked_schema_field_data = "{{ data.linked_schema_field }}"
      var schema_data = "{{ data.schema }}"
    </script>
    {{ form.select(
        'linked_schema_field',
        label=_('Linked schema field'),
        options=linked_schema_field[data.schema] if data.linked_schema_field else [],
        selected=data.linked_schema_field,
        error=errors.linked_schema_field,
        is_required=True
    ) }}

    {{ form.input(
        'name',
        id='field-name',
        label=_('Name'),
        value=data.name,
        error=errors.name,
        classes=['control-medium'],
        is_required=True
    ) }}

    {{ form.select(
        'type',
        label=_('Type'),
        options=h.get_vocabulary_service_types(),
        selected=data.type,
        error=errors.type,
        is_required=True
    ) }}

    {{ form.input(
        'uri',
        id='field-uri',
        label=_('URI'),
        value=data.uri,
        error=errors.uri,
        classes=['control-medium'],
        is_required=True
    ) }}

    {{ form.select(
        'update_frequency',
        label=_('Update frequency'),
        options=h.get_vocabulary_service_update_frequencies(),
        selected=data.update_frequency,
        error=errors.update_frequency,
        is_required=True
    ) }}

    {{ form.checkbox(
        'allow_duplicate_terms',
        id='field-allow-duplicate_terms',
        label=_('Allow duplicate terms'),
        value=True,
        checked="checked" if data.allow_duplicate_terms else "",
        error=errors.allow_duplicate_terms,
        classes=['control-medium']
    ) }}

    {{ form.checkbox(
        'is_hierarchical',
        id='field-is-hierarchical',
        label=_('Is hierarchical'),
        value=True,
        checked="checked" if data.is_hierarchical else "",
        error=errors.is_hierarchical,
        classes=['control-medium']
    ) }}

    {% if is_update %}
        {{ form.hidden('id', value=data.id) }}
    {% endif %}

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">{{ _('Update') if is_update else _('Add vocabulary service') }}</button>
    </div>

  </form>

  <hr />

  <h2>Vocabulary services</h2>

    <style>
        table.vocabs tr td {
            border: none;
        }
        table details {
            display: inline-block;
        }
        tr.odd {
            background-color: #f8f8f8;
        }
        tr.even {
            background-color: transparent;
        }
    </style>

  {% if services %}
    <h3>Total: {{ services|length }}</h3>
    <table class="table vocabs">
      <thead>
        <th width="35%">Title</th>
        <th width="12%">Terms</th>
        <th width="25%">Actions</th>
      </thead>
      <tbody>
        {% set all_linked_schema_field = h.get_linked_schema_field_options([], []) %}
        {% for service in services %}
        <tr class="{{ 'even' if loop.index % 2 == 0 else 'odd' }}">
          <td>
              <strong>
                  <a title="Click to view terms" href="{{ h.url_for('vocabulary_services.terms', id=service.id) }}">{{ service.title }}</a>
              </strong>
              <br />
              <small>
                  {% if service.schema|trim|length > 0 %}
                    <strong>Schema:</strong>&nbsp;
                      {%- for schema in schemas -%}
                        {%- if schema.value == service.schema -%}
                          {{- schema.text -}}
                        {%- endif -%}
                      {%- endfor -%}
                    <br />
                  {%- endif -%}
                  {% if service.schema|trim|length > 0 %}
                    <strong>Linked schema field:</strong> {{ h.get_linked_schema_field_label(all_linked_schema_field, service.schema, service.linked_schema_field) }}
                    <br />
                  {%- endif -%}
                  <strong>Name:</strong> {{ service.name }}
                  <br />
                  <strong>Allow duplicate terms:</strong> {{ "Yes" if service.allow_duplicate_terms else "No" }}
                  <br />
                  <strong>Is hierarchical:</strong> {{ "Yes" if service.is_hierarchical else "No" }}
              </small>
              <br />
              <span class="label label-primary{% if service.type == 'vocprez' %}success{% else %}default{% endif %}">{{ service.type }}</span>
          </td>
          <td>
            <a href="{{ h.url_for('vocabulary_services.terms', id=service.id) }}">View terms</a>
          </td>
          <td>
            <a href="{{ h.url_for('vocabulary_services.refresh', id=service.id) }}" class="btn btn-sm btn-warning">Refresh</a>
            <a href="{{ h.url_for('vocabulary_services.index', id=service.id) }}" class="btn btn-sm btn-primary">Edit</a>
            <a href="{{ h.url_for('vocabulary_services.delete', id=service.id) }}" class="btn btn-sm btn-danger" data-module="confirm-action" data-module-content="Are you sure you want to delete this vocabulary service and its terms?">Delete</a>
          </td>
        </tr>
        <tr class="{{ 'even' if loop.index % 2 == 0 else 'odd' }}">
            <td colspan="3"><small>
                <details>
                    <summary>URI <span style="color: #bbb">(click to display)</span></summary>
                    URI: {{ service.uri }}
                </details>
            </small></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}

{% block secondary_content %}{% endblock %}

ckanext/vocabulary_services/templates/vocabulary/secure_upload.html
{% extends "admin/base.html" %}

{% import 'macros/form.html' as form %}

{% block primary_content_inner %}
    <h1>Secure vocabularies</h1>

    {% for vocabulary in config if vocabulary.enable_upload %}
        <h2>{{ vocabulary.title }}</h2>

        <form method="post" enctype="multipart/form-data">
            {{ h.csrf_input() }}
            <div class="form-group control-full">
                <label class="control-label" for="field-{{ vocabulary.name }}-upload">File</label>
                <div class="controls">
                    <input type="file" id="field-{{ vocabulary.name }}-upload" name="file_upload" value="" placeholder="" class="form-control" title="Upload a file from your computer">
                </div>
            </div>

            <input type="hidden" name="filename" value="{{ vocabulary.filename }}" />

            <div class="form-actions">
                <button type="submit" class="btn btn-primary" name="save">{{ _('Upload ' + vocabulary.title + ' CSV') }}</button>
            </div>
        </form>
        <hr />
    {% endfor %}
{% endblock %}

{% block secondary_content %}{% endblock %}

ckanext/vocabulary_services/templates/vocabulary/terms.html
{% extends "admin/base.html" %}

{% block primary_content_inner %}

  <a href="{{ h.url_for('vocabulary_services.index') }}">&lt; Back</a>

  <h1>{{ vocabulary_service.title }} <small>(Name: {{ vocabulary_service.name }})</small></h1>

  <h2>Vocabulary terms <a href="{{ h.url_for('vocabulary_services.refresh', id=vocabulary_service.id) }}" class="btn btn-sm btn-warning">Refresh</a></h2>

  {% if terms %}
    <h3>Total: {{ terms|length }}</h3>

    <p>
        Last updated: {% snippet 'snippets/local_friendly_datetime.html', datetime_obj=vocabulary_service.date_last_processed %}
    </p>

    <table class="table table-bordered table-striped">
      <tbody>
        {% for term in terms %}
        <tr class="{{ 'even' if loop.index % 2 == 0 else 'odd' }}">
          <td>
            <small>
              <strong>Label:</strong> {{ term.label }}<br/>
              <strong>URI:</strong> {{ term.uri }}<br/>
              {% if vocabulary_service.is_hierarchical %}
                <strong>Broader term:</strong> {{ term.broader }}<br/>
              {% endif %}
              <strong>Definition:</strong> {{ term.definition }}<br/>
              <strong>Quantity Kind:</strong> {{ term.quantity_kind }}<br/>
              <strong>Created:</strong> {{ term.date_created }}<br/>
              <strong>Updated:</strong> {{ term.date_modified }}<br/>
            </small>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}

{% block secondary_content %}{% endblock %}